version: '3.8'

services:
  web_app_204:
    build:
      context: ./nextjs_app  #path to Next.js app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - webapp_network
    command: tail -f /dev/null

  sat_solver_204:
    build:
      context: .  #path to Python app
      dockerfile: Dockerfile
    volumes:
      - .:/PROJECT  # Map Python app directory to /PROJECT in container
    ports:
      - "5000:5000"
    networks:
      - webapp_network
    command: tail -f /dev/null

networks:
  webapp_network:
    driver: bridge
